"""empty message

Revision ID: f75e941c8ad7
Revises: a688c5b5457b
Create Date: 2019-09-12 19:57:26.757735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75e941c8ad7'
down_revision = 'a688c5b5457b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Contacts', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Contacts', type_='unique')
    # ### end Alembic commands ###
